<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <title>Document</title>
</head>
<body>
    <header class="flex items-center bg-black">
        <a href=""><img src="/assets/images/logo.png" alt="logo" class="w-16 m-3" /></a>
        <h1 href="" class="text-white hover:underline">Funcionarios</h1>
    </header>
    <div class="flex items-center justify-center mt-12">
        <div id="input" class="">
            <form action="<?= route("barber.update") ?>" method="POST">
                <input
                    type="text"
                    class="bg-white border-gray-500 border-2 rounded-lg my-5 w-80 h-8 p-2"
                    placeholder="Nome do Funcionario*"
                    name="admin[name]"
                    required
                />
                <input
                    type="text"
                    class="bg-white border-gray-500 border-2 rounded-lg my-5 mx-5 w-80 h-8 p-2"
                    placeholder="email@gmail.com"
                    name="admin[email]"
                    required
                />
                <div class="flex items-center justify-center">
                    <a href="<?= route('barber.new') ?>" id="Excluir" class="bg-red-700 text-white rounded-full py-2 px-5 font-bold mr-5">CANCELAR</a>
                    <button type="submit" id="Atualizar" class="bg-blue-700 text-white rounded-full py-2 px-5 font-bold ml-5">ATUALIZAR</button>  
                </div>
                
            </form>
        </div>
    </div>
</body>
</html>


<script>
$(document).ready(function() {
    $("form").validate({ // Inicializa a validação do formulário
        rules: {
            "admin[name]": {
                required: true,
                minlength: 2,
                maxlength: 100
            },
            "admin[email]": {
                required: true,
                email: true
            }
        },
        messages: {
            "admin[name]": {
                required: "O nome do funcionário é obrigatório.",
                minlength: "O nome deve ter pelo menos 2 caracteres.",
                maxlength: "O nome deve ter no máximo 100 caracteres."
            },
            "admin[email]": {
                required: "O email é obrigatório.",
                email: "Por favor, insira um email válido."
            }
        }
    });

    // Adiciona classes CSS para estilização dos elementos inválidos
    $(".selector").addClass("invalid-feedback");
});
</script>