

<script src="https://cdn.tailwindcss.com"></script>
<title>Area do Admin</title>
<body>
    <div class="flex justify-center mt-8">
      <div id="scheduling" class="flex">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="red"
          class="bi bi-circle-fill"
          viewBox="0 0 16 16"
        >
          <circle cx="8" cy="8" r="8" />
        </svg>
        <h1>Agendado</h1>
      </div>
      <div id="finish" class="flex">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="green"
          class="bi bi-circle-fill"
          viewBox="0 0 16 16"
        >
          <circle cx="8" cy="8" r="8" />
        </svg>
        <h1>Finalizado</h1>
      </div>
      <div id="cancel" class="flex">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="yellow"
          class="bi bi-circle-fill"
          viewBox="0 0 16 16"
        >
          <circle cx="8" cy="8" r="8" />
        </svg>
        <h1>Cancelado</h1>
      </div>
    </div>
    <tbody>
        <div class="flex justify-center mt-8 ">
            <h1>Data: </h1> 
            <h1 class="mx-3">Serviço:  </h1> 
            <h1 class="mx-3">Barbeiro: </h1>
            <h1>Local: </h1>
        </div>
    </tbody>
  </body>