<header class="flex items-center bg-black">
        <a href="<?= route('users.logout') ?>"><img src="/assets/images/logo.png" alt="logo" class="w-16 m-3" /></a>
  
        <a href="<?= route('barber.new') ?>" class="text-white hover:underline"><?= $title1?></a>
    </header>

<body>
    <div class="flex justify-center mt-8">
      <div id="scheduling" class="flex">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="red"
          class="bi bi-circle-fill"
          viewBox="0 0 16 16"
        >
          <circle cx="8" cy="8" r="8" />
        </svg>
        <h1>Agendado</h1>
      </div>
      <div id="finish" class="flex">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="green"
          class="bi bi-circle-fill"
          viewBox="0 0 16 16"
        >
          <circle cx="8" cy="8" r="8" />
        </svg>
        <h1>Finalizado</h1>
      </div>
      <div id="cancel" class="flex">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="yellow"
          class="bi bi-circle-fill"
          viewBox="0 0 16 16"
        >
          <circle cx="8" cy="8" r="8" />
        </svg>
        <h1>Cancelado</h1>
      </div>
    </div>
    <tbody>
      <?php foreach ($schedules as $scheduling) : ?>
            <tr>
                <td>
                <div class="flex justify-center mt-8 ">
                  <h1>Data: <?= $scheduling->date_scheduling ?></h1> 
                  <h1 class="mx-3">Serviço:  <?= $scheduling->service ?></h1> 
                  <h1 class="mx-3">Barbeiro: <?= $scheduling->barber ?></h1>
                  <h1>Local: <?= $scheduling->local ?></h1>
                </div>
                </td>
            </tr>
      <?php endforeach; ?>
    </tbody>
  </body>