<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>
    <header class="flex items-center bg-black">
        <a href=""><img src="/assets/images/logo.png" alt="logo" class="w-16 m-3" /></a>
        <h1 href="" class="text-white hover:underline">Funcionarios</h1>
    </header>

    <tbody>
        <?php foreach ($barbers as $barber) : ?>
            <tr>
                <td>
                <div class="flex justify-center mt-10 ">
                    <div class="flex">
                        <h1 class="font-bold mx-2">Nome:</h1>
                        <h1> <?= $barber->name ?></h1>
                    </div>
                    <div class="flex">
                        <h1 class="font-bold mx-2">Email:</h1>
                        <h1> <?= $barber->email ?></h1>
                    </div>
                    <div class="d-flex flex-row-reverse">
                        <form action="<?= route('admin.destroy', ['id' => $barber->id]) ?>" method="POST" class="m-0">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-link"><i class="bi bi-archive"></i></button>
                        </form>
                        <a href="<?= route('barber.edit', ['id' => $barber->id]) ?>" class="btn btn-link pe-0">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    </div>
                </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <div class="flex items-center justify-center mt-5">
        <a href="<?= route('admin.show') ?>" class="bg-blue-700 text-white rounded-full py-2 px-5 font-bold ml-5 flex items-center justify-center">CRIAR FUNCIONARIO</a>
    </div>
</body>
</html>