<form id="container" action="/login" method="POST" class="flex flex-col bg-zinc-900 items-center justify-center my-12 mx-96 rounded-lg">
        
        <h1 class="font-bold text-white text-4xl mt-5">LOGIN</h1>
        <div class="flex flex-col text-xs ">
        <img src="/assets/images/logo.png" alt="Logo" class="w-48 ml-16" />
            <input type="email" id="container" placeholder="E-mail" class="rounded-full my-5 w-80 px-3 py-2" name="user[email]"/>
        
            <input type="password" id="container" placeholder="Senha" class="rounded-full mb-5 px-3 py-2" name="user[password]"/>
        </div>

        <div class="bg-sky-500 mt-2 py-2 px-5 rounded-full font-bold text-white">
            <input type="submit" value="LOGIN">
        </div>

        <p class="mt-3 mb-5 text-white"> Não possui uma conta? <a href="/pages/register/index.php" class="text-sky-500"> Cadastre-se</a> aqui! </p>
</form>

<!--
<form action="/login" method="POST">
    <div class="form-group mb-3">
        <label for="user_email" class="form-label">Email</label>
        <input id="user_email" type="email" name="user[email]" class="form-control" placeholder="Enter email">
    </div>
    <div class="form-group mb-3">
        <label for="user_password" class="form-label">Senha</label>
        <input id="user_password" type="password" name="user[password]" class="form-control" placeholder="Password">
    </div>
    <div class="d-grid">
        <input type="submit" class="btn btn-primary btn-block" value="Entrar">
    </div>
</form>
-->
