<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="shortcut icon"
      href="/assets/img/logo.png"
      type="image/x-icon"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>
    <header class="flex items-center justify-between bg-black px-4 py-2">
        <div class="flex items-center">
            <img src="/assets/img/Logo.png" alt="logo" class="w-16 m-3" />
            <a href="/pages/user/list.php" class="text-white">Area do Usuario</a>
            <a href="/pages/scheduling/list.php" class="text-white ml-5">Agendamentos</a>
        </div>
        <a href="/pages/scheduling/new.php" class="text-white bg-orange-700 py-3 px-4 font-bold">AGENDE SEU HORÁRIO</a>
    </header>
    <div>
        <img src="/assets/img/background.jpg" alt="barbearia" class="w-screen h-screen object-cover">        
    </div>
  
</body>
</html>