<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="./assets/img/logo.png"
      type="image/x-icon"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>User</title>
  </head>
  <body>
    <div class="flex">
      <div id="image-user" class="m-10">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="250"
          height="250"
          fill="grey"
          class="bi bi-person-circle"
          viewBox="0 0 16 16"
        >
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0" />
          <path
            fill-rule="evenodd"
            d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"
          />
        </svg>
      </div>
      <div id="input" class="flex flex-col aling-center justify-center ml-14">
        <div>
          <input
            type="text"
            class="bg-white border-gray-500 border-2 rounded-lg my-5 w-80 h-8 p-2"
            placeholder="Nome Completo*"
            required
          />
          <input
            type="text"
            class="bg-white border-gray-500 border-2 rounded-lg my-5 mx-5 w-80 h-8 p-2"
            placeholder="email@gmail.com*"
            required
          />
        </div>
        <div>
          <input
            type="text"
            class="bg-white border-gray-500 border-2 rounded-lg my-5 w-80 h-8 p-2"
            placeholder="() 00000-0000*"
            required
          />
          <input
            type="text"
            class="bg-white border-gray-500 border-2 rounded-lg my-5 mx-5 w-80 h-8 p-2"
            placeholder="Senha"
          />
        </div>
        <div id="button" class="flex justify-center mt-12">
          <button id="Excluir" class="bg-red-700 text-white rounded-full py-2 px-5 font-bold mr-5">EXCLUIR CONTA</button>
          <button id="Atualizar" class="bg-blue-700 text-white rounded-full py-2 px-5 font-bold ml-5">ATUALIZAR DADOS</button>
        </div>
      </div>
    </div>
  </body>
</html>